### ISSUE TITLE
Angle.hpp :  M_PI is still causing issues.

### ISSUE THREAD

**Issue by Yaluzan** [HU-R2D2/adt#10]
`57:    static constexpr double M_PI = 3.14159265358979323846;`
Is causing errors because of the naming of M_PI
This can be fixed by renaming it to m_PI
Just have to make sure the Angle.cpp and one more line in Angle.hpp get updated so it supports that
Lines that will need to be adjusted for the M_PI name change
Angle.hpp: 57 & 60
Angle.cpp: 44

(unsure about tests, but that will be discovered during testing)

This is in regards to the master branch, maybe it has been fixed in that pull request that still has to be approved?

**Comment by martijnvandijk** [comment]
Should be fixed in #9  - can you test it?

**Comment by CasperTI** [comment]
Is no longer a constexpr in master, using cmath M_PI now instead.
