### ISSUE TITLE
Box::get_intersection_box() geeft verkeerde waarden terug

### ISSUE THREAD

**Issue by ScottMackay2** [HU-R2D2/adt#17]
(Map interface is afhangkelijk van dit probleem)
De get_intersection_box() lijkt niet te werken van ADT. Ik kijk naar de code en het lijkt helemaal niet te doen wat het moet doen. 
        Bij een input van (Template: box(x0,y0,z0, x1,y1,z1)):
        (0,0,0, 2,2,1) + (1,1,0, 3,3,1)
        Krijg ik als antwoordt van de functie get_intersection_box():
        (0,0,0, 3,3,1)
        Het had:
        (1,1,0, 2,2,1) moeten zijn :/

**Comment by CasperTI** [comment]
Fix staat klaar in hotfix-box branch, is nu naar client voor goedkeuring
