### ISSUE TITLE
Box::getIntersctionBox undocumented behaviour

### ISSUE THREAD

**Issue by martijnvandijk** [HU-R2D2/adt#4]
The code below from box.cpp returs a box with a size of 0. This is not documented. Simply stating that it will return a box with a size of 0 in the `@return` doxygen statement will suffice.

```
Box Box::getIntersectionBox(Box box)
{
    if(this->intersects(box))
    {
        // return intersection box
        if(this->contains(box.bottomLeft))
        {
            // intersectionBox bottomLeft
            return Box(box.getBottomLeft(), topRight);
        }
        else
        {
            return Box(bottomLeft, box.getTopRight());
        }
    }
    else
    {
        // no intersection box
        return Box(Coordinate(0.0,0.0,0.0), Coordinate(0.0,0.0,0.0));
    }
```

**Comment by StephanVV** [comment]
Have added note to doxygen in: https://github.com/HU-R2D2/adt/commit/70d6f211626cbd76877f01b15d35006480f68f6b 
And return param in: https://github.com/HU-R2D2/adt/commit/eb2704f0f0285eb8a2afc4da7c677ba06f78a470
