### ISSUE TITLE
Duration return value bug

### ISSUE THREAD

**Issue by martijnvandijk** [HU-R2D2/adt#5]
These methods return seconds instead of duration objects.

```

Duration Duration::operator* (const double& rhs) const{
    double result = seconds * rhs;
    return result;
}

Duration Duration::operator/ (const double& rhs) const{
    double result = seconds;
    return result;
}
```

**Comment by JobVerhaar** [comment]
Fixed it by replacing it by:
Duration Duration::operator\* (const double& rhs) const{
    return Duration{seconds \* rhs};
}

Duration Duration::operator/ (const double& rhs) const{
    return Duration{seconds / rhs};
}
